---
title: "filter_join"
author: "Melissa Anderson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(here) 
library(kableExtra)

dt <- mtcars[1:5, 1:6]
```

```{r echo=FALSE}
# Read in data: 
fish <- read_csv(here("data", "fish.csv"),show_col_types = FALSE)
kelp_abur <- read_excel(here("data", "kelp.xlsx"), sheet = "abur")

fish_garibaldi <- fish %>% 
  filter(common_name == "garibaldi")

fish_mohk <- fish %>% 
  filter(site == "mohk")

fish_over50 <- fish %>% 
  filter(total_count >= 50)

fish_3sp <- fish %>% 
  filter(common_name == "garibaldi" | 
           common_name == "blacksmith" | 
           common_name == "black surfperch")

fish_3sp <- fish %>% 
  filter(common_name %in% c("garibaldi", "blacksmith", "black surfperch"))

fish_gar_2016 <- fish %>% 
  filter(common_name == "garibaldi" | 
           year == 2016
  )

aque_2018 <- fish %>% 
  filter(year == 2018, site == "aque")

 low_gb_wr <- fish %>% 
   filter(common_name %in% c("garibaldi", "rock wrasse"), 
          total_count <= 10)

fish_bl <- fish %>% 
  filter(str_detect(common_name, pattern = "black")) 

fish_it <- fish %>% 
  filter(str_detect(common_name, pattern = "it")) 

abur_kelp_fish <- kelp_abur %>% 
  full_join(fish, by = c("year", "site")) 

kelp_fish_left <- kelp_abur %>% 
  left_join(fish, by = c("year","site"))

kelp_fish_injoin <- kelp_abur %>% 
  inner_join(fish, by = c("year", "site"))

# kelp_fish_injoin

my_fish_join <- fish %>% 
  filter(year == 2017, site == "abur") %>% 
  left_join(kelp_abur, by = c("year", "site")) %>% 
  mutate(fish_per_frond = total_count / total_fronds)

my_fish_join %>%
  kbl(caption = "Table 1: All the Fish") %>%
  kable_classic(html_font = "Cambria")

```
*Fish are known to be a thing...*
