---
title: "my_tidying"
author: "Melissa Anderson"
date: "`r Sys.Date()`"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Attach packages
library(tidyverse)
library(janitor)
library(here)
library(readxl)

inverts <- read_excel(here("data", "inverts.xlsx"))
```


```{r echo=TRUE}
inverts_long <- pivot_longer(data = inverts, 
                                    cols = '2016':'2018',
                                    names_to = "year",
                                    values_to = "sp_count")
inverts_long <- inverts_long %>% 
  mutate(year = as.numeric(year))

inverts_wide <- inverts_long %>% 
  pivot_wider(names_from = common_name, 
                     values_from = sp_count)

inverts_wide <- inverts_wide %>% 
  clean_names()

inverts_unite <- inverts_long %>% 
  unite(col = "site_year", # What to name the new united column
               c(site, year), # The columns we'll unite (site, year)
               sep = "_") # How to separate the things we're uniting

inverts_unite_month <- inverts_long %>% 
  unite(col = "month_year", # What to name the new united column
               c(month, year), # The columns we'll unite (site, year)
               sep = "/") # How to separate the things we're uniting

inverts_sep <- inverts_unite %>% 
  tidyr::separate(site_year, into = c("my_site", "my_year"))

ca_abbr <- inverts %>% 
  mutate(
    common_name = 
      str_replace(common_name, 
              pattern = "california", 
              replacement = "CA")
  )

```

