---
title: "pivot_lobsters"
author: "Melissa Anderson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## attach libraries
library(tidyverse)
library(readxl)
library(here)
library(skimr) # install.packages('skimr')
library(kableExtra) # install.packages('kableExtra')
```

```{r}
## read in data
lobsters <- read_xlsx(here("data/lobsters2.xlsx"), skip=4)

# explore data
skimr::skim(lobsters) 
```
```{r include=FALSE}
siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(), 
            mean_size_mm = mean(size_mm, na.rm = TRUE),
            median_size_mm = median(size_mm, na.rm = TRUE),
            sd_size_mm = sd(size_mm, na.rm = TRUE))
## `summarise()` regrouping output by 'site' (override with `.groups` argument)
## inspect our new variable 
siteyear_summary 
```
```{r}
## make a table with our new variable
siteyear_summary %>%
  kable()
```

There are `r count(lobsters)` total lobsters included in this report.
```{r}
ggplot(data = siteyear_summary, aes(x=year, y=median_size_mm,color=site)) +
  geom_line() +
  facet_wrap(~ site)
ggsave(here("figures", "lobsters-col.png"))
## Saving 7 x 5 in image
```

```{r}
lobsters_detailed <- lobsters %>%
  mutate(size_m = size_mm / 1000, 
         millenia = 2000,
         observer = "Allison Horst")

lobsters_detailed %>%
  select(date, site, size_m) %>%
  kable()
```

